version: '3.7'
services:
  elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node    
    ports:
    - '9200:9200'
    - '9300:9300'
    networks:
      - otelelk

  logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
    - '${PWD}/logstash/pipeline/:/usr/share/logstash/pipeline/'
    - '${PWD}/logstash/nginx.log:/usr/share/logstash/nginx.log'
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf 
    depends_on:
      - elasticsearch
    ports:
    #- '5044:5044'
    #- '5000:5000/tcp'
    #- '5000:5000/udp'
    - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"    
    networks:
      - otelelk

  kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always       
    ports:
    - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200  
    depends_on:
      - elasticsearch  
    networks:
      - otelelk
volumes:
  elastic_data: {}

networks:
  otelelk: