version: '3.7'
services:
  opentelemetry-collector:
    ports:
      - '4317:4317'
    volumes:
      - '${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml'
    image: 'otel/opentelemetry-collector-contrib:0.77.0'
    #image: 'otel/opentelemetry-collector:0.77.0'

